nutrinova-ui/src/app/page.tsx

im the captain

---

.devcontainer/docker-compose.yml
.github/workflows/build.yml
.github/workflows/deploy.yml
ops/docker-compose.yml

- Got the devcontainer working again,
- moved out the prod db password n stuff to secrets

update devcontainer environment, db prod secrets

---

.github/workflows/deploy.yml
nutrinova-api/.editorconfig
nutrinova-api/NutrinovaApi/.gitignore
nutrinova-api/NutrinovaApi/Controllers/CustomerController.cs
nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
nutrinova-api/NutrinovaApi/NutrinovaApi.csproj
nutrinova-api/NutrinovaApi/Program.cs
nutrinova-api/NutrinovaApi/appsettings.Development.json
nutrinova-api/NutrinovaApi/appsettings.json
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFood.cs
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFoodNutrient.cs
nutrinova-api/NutrinovaData/ResponseModels/Food.cs
nutrinova-api/NutrinovaData/ResponseModels/FoodNutrient.cs
nutrinova-api/NutrinovaData/ResponseModels/FoodSearchCriteria.cs
nutrinova-api/NutrinovaData/ResponseModels/FoodSearchResponseModel.cs
nutrinova-ui/src/app/api/auth/[...nextauth]/options.ts
nutrinova-ui/src/app/api/auth/[...nextauth]/route.ts
nutrinova-ui/src/app/page.tsx
ops/docker-compose.yml

This is the first implementation of the the food controller with just the search end point made. @Cwighty and @andrewbengordon let me know what you think and if it seems right we can merge this so caleb can work with real data while I implement the getFoodByID endpoint.

Updating endpoints for food search

---

README.md

We may need to try and get more done earlier on, I felt like there was quite a bit crammed in at the last week.

Add dates to readme

---

nutrinova-ui/src/app/(public)/welcome/page.tsx

UseSession doesn't work very well in prod for some reason, getSession works better

Fix user session not getting id in prod

---

nutrinova-ui/src/app/(public)/auth/signin/page.tsx
nutrinova-ui/src/app/page.tsx
nutrinova-ui/src/components/NavigationList.tsx
nutrinova-ui/src/middleware.ts
nutrinova-ui/src/services/customerService.ts

- Add sign out
- Add landing page when not signed in
- Automatically redirect to keycloak for sign in / sign up instead of the button
- Automatically redirects to correct pages if new customer or not
I did use useSession again which i know we had trouble with in production in the past. If it doesnt work again I'll try and replace it with getSession

Smooth out the authentication experience

---

.vscode/settings.json
nutrinova-api/.editorconfig
nutrinova-api/NutrinovaApi.IntegrationTests/FoodControllerTests.cs
nutrinova-api/NutrinovaApi.IntegrationTests/NutrinovaApiWebApplicationFactory.cs
nutrinova-api/NutrinovaApi.IntegrationTests/TestAuthHandler.cs
nutrinova-api/NutrinovaApi.IntegrationTests/TestAuthHandlerOptions.cs
nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFood.cs
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFoodNutrient.cs
nutrinova-ui/src/app/(authorized)/dashboard/page.tsx

Commented out the other test because they where some how sharing a database and messing each other up. Left one test in that covers most of the functionality. I made sure all the other tests passed when ran individually.

Adding more search filters for all foods api

---

.github/workflows/pull_request_checks.yml
README.md

Updated it what we have so far for nov 4th and 11th

Update README.md For the week

---

nutrinova-api/NutrinovaData/ResponseModels/FoodNutrientConverter.cs
nutrinova-ui/package-lock.json
nutrinova-ui/src/app/(authorized)/food/create/_components/AddNutrientDialog.tsx
nutrinova-ui/src/app/(authorized)/food/view/_components/MyFoodsSearchForm.tsx
nutrinova-ui/src/components/forms/NutrientFilterOptions.tsx
nutrinova-ui/src/components/forms/SelectNutrient.tsx

Fixed the created food to show up on view details. Seperated the select nutrient and the compare nutrients components.

Bug fixes for nutrient

---

nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/FoodControllerTests.cs
nutrinova-api/NutrinovaApi/Controllers/FoodController.cs

spelling changes and more comprehensive test changes.

Made some spelling changes and test changes

---

nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/FoodControllerTests.cs
nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
nutrinova-api/NutrinovaData/Extensions/FoodPlansExtension.cs
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFood.cs
nutrinova-api/NutrinovaData/RequestModels/EditFoodNutrientRequestModel.cs
nutrinova-api/NutrinovaData/RequestModels/EditFoodRequestModel.cs
nutrinova-api/NutrinovaData/ResponseModels/Food.cs

added the edit food api endpoint had to disjoint the saving of the new food and the deletion of the rows in the association table.

New Edit Food api endpoint

---

.devcontainer/Dockerfile
nutrinova-ui/src/app/(authorized)/food/search/_components/SearchResultDataGrid.tsx
nutrinova-ui/src/app/(authorized)/food/view/_components/MyFoodsSearchResultDataGrid.tsx
nutrinova-ui/src/app/(public)/welcome/page.tsx
nutrinova-ui/src/components/data-grid/NoFoodRowsOverlay.tsx

- Dotnet 8 made the devcontainer fail installing dotnet without a version
- Added search term to the "no Foods Found" message/ better feedback for the user
- Made the circle arrow go right on the welcome page like alex suggested

I just need a quick win

---

nutrinova-ui/src/app/(authorized)/food/create/_components/AddNutrientDialog.tsx
nutrinova-ui/src/app/(authorized)/food/create/_components/CreateFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/create/_models/createFoodNutrientRequestModel.ts
nutrinova-ui/src/app/(authorized)/food/edit/_components/EditFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/edit/_models/editFoodRequest.ts

Got some better validation. 
- some of the classes used might be able to be consolidated Mainly the createfoodrequestmodel and the editfoodrequestmodel. 
take a look at them and let me know if you think I should consolidate them?
- Make sure I have all the things that should be edited on a food

Got adding a nutrient on the edit page.

---

nutrinova-ui/src/app/(authorized)/food/view/_components/MyFoodsSearchForm.tsx
nutrinova-ui/src/app/(authorized)/recipes/create/_components/AddFoodDialog.tsx
nutrinova-ui/src/components/forms/AmountInput.tsx
nutrinova-ui/src/components/forms/NutrientFilterOptions.tsx
nutrinova-ui/src/components/forms/SelectNutrient.tsx

Made the add foods form more mobile and modal friendly when adding from a recipe

Add foods to recipe styling

---

nutrinova-ui/src/app/(authorized)/food/edit/_components/EditFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/edit/page.tsx
nutrinova-ui/src/app/(authorized)/food/foodHooks.ts

Fixed the weird reload not rendering data and the navigating to the page after import not rendering. 
- The editformState was being set before the food query finished

Fixing reload edit page

---

nutrinova-api/NutrinovaData/Entities/RecipeHistory.cs
nutrinova-api/NutrinovaData/Entities/RecipePlan.cs
nutrinova-api/NutrinovaData/Entities/Unit.cs
nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
nutrinova-db/init-scripts/A_schema.sql

Recipes Didn't have a serving size on the actual recipe.
- We will need to update the view recipe page to have the serving size.

updated the recipes to have a serving amount

---

.github/workflows/deploy.yml

Update deploy.yml for no-cache?

---

.github/workflows/deploy.yml
nutrinova-ui/package-lock.json
nutrinova-ui/src/app/(authorized)/recipes/create/_components/ServingSizeUnitField.tsx
nutrinova-ui/src/app/(authorized)/recipes/edit/_components/EditRecipeForm.tsx
nutrinova-ui/src/components/forms/TagInput.tsx

made the edit recipe ui a little better

New recipe UI

---

nutrinova-api/NutrinovaApi/Controllers/MealController.cs
nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
nutrinova-ui/src/app/api/auth/[...nextauth]/options.ts
nutrinova-ui/src/app/page.tsx
nutrinova-ui/src/components/providers/QueryClientNextProvider.tsx
nutrinova-ui/types/next-auth.d.ts

Fix Sign-out to actually sign out, Sign in correctly

---

nutrinova-api/NutrinovaApi/Controllers/MealController.cs
nutrinova-api/NutrinovaApi/Controllers/RecipeController.cs
nutrinova-api/NutrinovaData/Extensions/RecipePlanExtension.cs
nutrinova-api/NutrinovaData/Features/Nutrients/NutrientSummary.cs
nutrinova-api/NutrinovaData/Features/Recipes/RecipeFoodTotaler.cs
nutrinova-api/NutrinovaData/RequestModels/UnitCategoryRequestModel.cs
nutrinova-api/NutrinovaData/ResponseModels/RecipeResponseModel.cs
nutrinova-ui/src/app/(authorized)/food/edit/_components/EditFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/edit/_components/EditNutrientListItem.tsx
nutrinova-ui/src/app/(authorized)/food/search/_components/SearchFoodsDetailCard.tsx
nutrinova-ui/src/app/(authorized)/food/view/_components/MyFoodsDetailCard.tsx
nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts
nutrinova-ui/src/app/(authorized)/meals/record/_components/MealItemSelector.tsx
nutrinova-ui/src/app/(authorized)/meals/record/_components/RecordMealStepper.tsx
nutrinova-ui/src/app/(authorized)/recipes/create/_components/NutrientTotalsSummary.tsx
nutrinova-ui/src/app/(authorized)/recipes/create/_models/recipe.ts
nutrinova-ui/src/app/(authorized)/recipes/view/_components/MyRecipesDetailCard.tsx
nutrinova-ui/src/components/providers/NotificationProvider.tsx

- The Import spinner had disappeared at some point
- Added some padding on the food edit
- added the nutrient summaries to the recipe detail, touched up how it looks everywhere its used
- Websockets seemed to go stale after a while and disconnect, think i fixed it
- Touched up the meal record selector, gets all meal items by default, and then lets you filter

Some Small Fixes

---

nutrinova-ui/src/app/(authorized)/food/foodHooks.ts

made the param use the axios correct

---

nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
nutrinova-api/NutrinovaData/Features/Units/UnitConverter.cs
nutrinova-api/NutrinovaData/FlattenedResponseModels/FlattenedFood.cs
nutrinova-api/NutrinovaData/ResponseModels/Food.cs

Milligram was misspelled. I think that fixed it

Removed the primary nutrient thing and fixed the iron import

---

.github/workflows/build.yml
nutrinova-ui/src/app/(authorized)/food/search/_components/SearchResultDataGrid.tsx
nutrinova-ui/src/app/(authorized)/meals/record/_components/MealDetailsStep.tsx
nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
nutrinova-ui/src/app/(authorized)/recipes/create/_components/AddFoodDialog.tsx
nutrinova-ui/src/components/forms/AmountInput.tsx

- make add food a stepper stepper in recipe creation
- fix patient mutation not invalidating query
- validate recording meals

Some fixes

---

.github/workflows/deploy.yml
nutrinova-api/NutrinovaApi/Controllers/ChatController.cs
nutrinova-api/NutrinovaApi/Controllers/ConversionSampleController.cs
nutrinova-api/NutrinovaApi/Controllers/CustomerController.cs
nutrinova-api/NutrinovaApi/Controllers/FoodController.cs
nutrinova-api/NutrinovaApi/Controllers/MealController.cs
nutrinova-api/NutrinovaApi/Controllers/NutrientController.cs
nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
nutrinova-api/NutrinovaApi/Controllers/RecipeController.cs
nutrinova-api/NutrinovaApi/Controllers/UnitController.cs
nutrinova-api/NutrinovaApi/GlobalUsings.cs
nutrinova-api/NutrinovaApi/NutrinovaApi.csproj
nutrinova-api/NutrinovaApi/Program.cs
nutrinova-api/NutrinovaData/Entities/ChatMessage.cs
nutrinova-api/NutrinovaData/Entities/ChatSession.cs
nutrinova-api/NutrinovaData/Entities/Customer.cs
nutrinova-api/NutrinovaData/Features/Chat/ChatMessageExtensions.cs
nutrinova-api/NutrinovaData/Features/Chat/ChatMessageResponse.cs
nutrinova-api/NutrinovaData/Features/Chat/INovaChatService.cs
nutrinova-api/NutrinovaData/Features/Chat/NovaChatService.cs
nutrinova-api/NutrinovaData/NutrinovaData.csproj
nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
nutrinova-api/NutrinovaData/RequestModels/NewChatMessageRequest.cs
ops/docker-compose.yml

Working api for chatting with Nova the nutritional assistant.
The api key can be added in secrets (theres an example in appsettings of what it looks like), or like the usda api key in the .env.local as `OpenAIServiceOptions__ApiKey=<apikey>`
You might get some free starter credit and an api key from signing up a new open ai api account, if not I can send you my key

Nova Chat Api

---

nutrinova-api/NutrinovaApi.IntegrationTests/TestAuthHandler.cs
nutrinova-api/NutrinovaApi/Controllers/CustomerController.cs
nutrinova-ui/src/app/(public)/welcome/page.tsx
nutrinova-ui/src/services/customerService.ts

I didn't realize that there was a patient controller class and how the first patient was being made. Put the code back into place and seems to work

Making single user own patient

---

.github/workflows/api_integration_tests.yml
nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/MealControllerTests.cs
nutrinova-api/NutrinovaApi/Controllers/MealController.cs
nutrinova-api/NutrinovaData.UnitTests/Features/Recipes/RecipeFoodTotaler.feature.cs
nutrinova-api/NutrinovaData/Features/Meals/EditMealRequest.cs
nutrinova-ui/src/app/(authorized)/meals/edit/EditMealForm.tsx
nutrinova-ui/src/app/(authorized)/meals/edit/EditMealModal.tsx
nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts
nutrinova-ui/src/app/(authorized)/meals/view/_components/MealDetailCard.tsx
nutrinova-ui/src/app/(authorized)/meals/view/_models/viewMeal.ts

- Made the edit meal modal
- Added the delete meal endpoint
- Added authorization that the person editing/deleting a meal is the customer linked to the patient who the meal is linked to

Meal edit frontend

---

nutrinova-api/NutrinovaData/Entities/Patient.cs
nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
nutrinova-db/init-scripts/A_schema.sql

Update patients table for database.

updated data base.

---

nutrinova-api/NutrinovaApi/Controllers/PatientController.cs

check to see if the picture name is null or not.

---

.gitignore

Got it from the drinking fountain I swear

added mono to the gitignore

---

nutrinova-api/NutrinovaApi/Controllers/GoalController.cs
nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
nutrinova-api/NutrinovaData/Entities/Patient.cs
nutrinova-api/NutrinovaData/Features/Patients/CreatePatientRequest.cs
nutrinova-api/NutrinovaData/Features/Patients/PatientExtension.cs
nutrinova-api/NutrinovaData/Features/Patients/PatientResponse.cs
nutrinova-api/NutrinovaData/NutrinovaDbContext.cs
nutrinova-db/init-scripts/A_schema.sql
nutrinova-ui/src/app/(authorized)/patients/_models/patient.ts
nutrinova-ui/src/app/(authorized)/patients/page.tsx
nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx
nutrinova-ui/src/app/(public)/addpatients/_components/PatientListItem.tsx
nutrinova-ui/src/app/(public)/addpatients/page.tsx
nutrinova-ui/src/app/(public)/welcome/page.tsx

it is better
___
enhancement, bug_fix
___
- Made `age` a required field and added `optOut` boolean field in the `Patient` model.
- Refactored Patients Page to use `PatientListItem` component and improved layout with Paper and Grid components.
- Implemented opt-out details handling in patient creation and listing.
- Updated database schema and entity models to reflect changes in patient age and opt-out details.
- Fixed nutrient recommendation logic to use non-nullable age.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td>
<details>
<summary><strong>patient.ts</strong><dd><code>Update Patient Model to Include Mandatory Age and Opt-Out …

Patient info page

---

nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/PatientControllerTests.cs
nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
nutrinova-db/init-scripts/A_schema.sql
nutrinova-ui/src/app/(authorized)/patients/page.tsx
nutrinova-ui/src/app/(authorized)/patients/patientHooks.tsx

FE and BE are done
___
enhancement, bug_fix
___
- Added functionality for deleting patients in the frontend and backend, including necessary hooks and error handling.
- Implemented integration tests for the new patient deletion functionality, ensuring proper behavior.
- Updated the database schema to support cascading deletion, ensuring related data is also removed when a patient is deleted.
- Added checks to prevent the deletion of the last patient, maintaining data integrity.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Implement Patient Deletion Functionality with Error Handling</code></dd></summary>
<hr> …

Deleting patients

---

nutrinova-ui/src/app/(authorized)/food/create/_components/CreateFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/edit/_components/EditFoodForm.tsx
nutrinova-ui/src/app/(authorized)/food/edit/_components/EditNutrientListItem.tsx
nutrinova-ui/src/app/(authorized)/goals/CreateGoalModalContent.tsx
nutrinova-ui/src/app/(authorized)/meals/edit/EditMealForm.tsx
nutrinova-ui/src/app/(authorized)/meals/edit/EditMealModal.tsx
nutrinova-ui/src/app/(authorized)/recipes/create/_components/ServingSizeUnitField.tsx
nutrinova-ui/src/app/(authorized)/recipes/edit/_components/EditRecipeForm.tsx
nutrinova-ui/src/components/forms/AmountInput.tsx

enhancement, bug_fix
___
- Refactored and enhanced `EditFoodForm` and `EditRecipeForm` for better readability, validation, and error handling.
- Fixed handling of numeric inputs in various forms to ensure consistent type usage and validation.
- UI enhancements in `EditMealForm` and `EditMealModal` for better usability and appearance.
- Improved goal limit handling in `CreateGoalModalContent` for better consistency and validation.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details>
<summary><strong>CreateFoodForm.tsx</strong><dd><code>Convert servingSize to String in CreateFoodForm</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Number inputs

---

nutrinova-api/NutrinovaApi.IntegrationTests/ControllerTests/PatientControllerTests.cs
nutrinova-api/NutrinovaApi/Controllers/PatientController.cs
nutrinova-api/NutrinovaData/Features/Patients/UpdatePatientRequest.cs

Backend for making patient edit with test.

Edit patient back end

---

nutrinova-ui/src/app/(authorized)/dashboard/_components/Cards/DailyCalories.tsx
nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts

___
enhancement
___
- Integrated real meal data into the DailyCalories card using the newly added `useGetTodaysMealsQuery` hook.
- Removed static meal data and useEffect hook from DailyCalories card, enhancing data accuracy and performance.
- Added loading state visualization in the DailyCalories card to improve user experience during data fetching.
- Implemented dynamic meal period calculation (Morning, Afternoon, Evening) based on meal time.
- Modified the UI to dynamically display fetched meal data and handle cases where no data is available.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>DailyCalories.tsx</strong><dd><code>Integrate Real Meal Data into …

Connect actual meals to meal card on dashboard

---

.devcontainer/.dockerignore
docs/Features/Authentication/Authentication Overview.md
docs/Features/Foods/Foods Overview.md
docs/Features/Goals/Goals Overview.md
docs/Features/Goals/Nutrient Goal Types.md
docs/Features/Goals/Nutrient Summation.md
docs/Features/Meals/Meal Overview.md
docs/Features/Nova Chatbot/Nova Chat Overview.md
docs/Features/Patients/Paitent Overview.md
docs/Features/Recipes/Recipe Overview.md
nutrinova-ui/.dockerignore
nutrinova-ui/src/app/(authorized)/dashboard/_components/Cards/DailyCalories.tsx
nutrinova-ui/src/app/(authorized)/meals/mealHooks.ts

Convert Docs to Markdown and Place in Repo
